### ISSUE TITLE
Create a simple web api for minimal sample archive file downloads/uploads.

### ISSUE THREAD

**Issue by WhiteEyeDoll** [WhiteEyeDoll/SampleCloud#2]
**/about**
- **/package**
  - [x] /info
  - [x] /release
  - [x] /maintainer

**/data**
- **/samples**
  - [ ] /download
  - [ ] /upload 
  - [ ] /search
  - [ ] /info

**/users**
- **/login**
  - [ ] /normal

**Comment by evilon** [comment]
How about if the first release would just aim for providing the samples (e.g. download)?

**Comment by WhiteEyeDoll** [comment]
This will be most likely the case.
